
init:
  '!gcpCredentials': $params.authWith
  appPath: /tmp/bqreplay
  functionName: BqTailReplay
  gcp: ${secrets.$gcpCredentials}
  serviceAccount: $gcp.ClientEmail
  prefix: $Replace(${gcp.ProjectID},'-','_')
  replayBucket: ${prefix}_replay
  triggerBucket: viant_dataflow_bqtail

pipeline:

  create:
    bucket:
      action: storage:create
      isDir: true
      dest:
        URL: gs://${replayBucket}/
        credentials: $gcpCredentials


  deploy:
    checkOut:
      action: vc/git:checkout
      Origin:
        URL: https://github.com/viant/bqtail.git
      Dest:
        URL: ${appPath}

    package:
      action: exec:run
      target: $target
      checkError: true
      commands:
        - cd ${appPath}
        - unset GOPATH
        - export GO111MODULE=on
        - rm -rf vendor
        - go mod vendor

    upload:
      action: gcp/cloudfunctions:deploy
      credentials: $gcpCredentials
      public: true
      '@name': $functionName
      entryPoint: Replay
      runtime: go111
      availableMemoryMb: 128
      timeout: 540s
      serviceAccountEmail: $serviceAccount
      environmentVariables:
        LOGGING: 'false'
      source:
        URL: ${appPath}/
      sleepTimeMs: 5000


  schedule:
    action: gcp/cloudscheduler:deploy
    credentials: $gcpCredentials
    init:
      body: $Cat('request.json')
    name: BqTailReplay
    schedule: 0 * * * *
    body: $body
    timeZone: GMT
    httpTarget:
      headers:
        User-Agent: Google-Cloud-Scheduler
      httpMethod: POST
      uri: https://us-central1-${gcp.ProjectID}.cloudfunctions.net/BqTailReplay