defaults:
  credentials: $gcpCredentials
init:
  AppVersion: $Cat(${appPath}/Version)

pipeline:

  deploy:
    set_sdk:
      action: sdk.set
      target: $target
      sdk: go:1.21

    package:
      action: exec:run
      comments: vendor build for deployment speedup
      target: $target
      checkError: true
      commands:
        - export GIT_TERMINAL_PROMPT=1
        - unset GOPATH
        - cd ${appPath}/
        - go mod vendor
        - go build
        - cd ${appPath}/cmd/bqtail
        - export GOOS=linux
        - export GOARCH=amd64
        - go build -ldflags "-X main.Version=${AppVersion}"
        - tar cvzf bqtail_linux_amd64_${AppVersion}.tar.gz bqtail
        - export GOOS=linux
        - export GOARCH=arm64
        - go build -ldflags "-X main.Version=${AppVersion}"
        - tar cvzf bqtail_linux_arm64_${AppVersion}.tar.gz bqtail
        - export GOARCH=arm64
        - export GOOS=darwin
        - go build -ldflags "-X main.Version=${AppVersion}"
        - tar cvzf bqtail_osx_arm64_${AppVersion}.tar.gz bqtail
        - export GOARCH=amd64
        - export GOOS=darwin
        - go build -ldflags "-X main.Version=${AppVersion}"
        - tar cvzf bqtail_osx_amd64_${AppVersion}.tar.gz bqtail
        - unset GOOS
        - go build -ldflags "-X main.Version=${AppVersion}"
        - cp bqtail /usr/local/bin

    deploay:
      bqtail:
        action: gcp/cloudfunctions:deploy
        '@name': BqTail
        timeout: 540s
        public: true
        availableMemoryMb: 256
        entryPoint: BqTail
        runtime: go121
        retry: true
        serviceAccountEmail: ${gcp.serviceAccount}
        environmentVariables:
          CONFIG: gs://${configBucket}/BqTail/config.json
          LOGGING: true
        eventTrigger:
          eventType: google.storage.object.finalize
          resource: projects/_/buckets/${triggerBucket}
        source:
          URL: ${appPath}/

      bqdisaptch:
        action: gcp/cloudfunctions:deploy
        '@name': BqDispatch
        timeout: 58s
        public: true
        serviceAccountEmail: ${gcp.serviceAccount}
        availableMemoryMb: 512
        entryPoint: BqDispatch
        runtime: go121
        environmentVariables:
          CONFIG: gs://${configBucket}/BqDispatch/config.json
          LOGGING: true
        source:
          URL: ${appPath}/

      scheduleDispatcher:
        action: gcp/cloudscheduler:deploy
        credentials: $gcpCredentials
        name: BqDispatch
        schedule: '*/1 * * * *'
        timeZone: GMT
        httpTarget:
          headers:
            User-Agent: Google-Cloud-Scheduler
          httpMethod: GET
          uri: https://${region}-${gcp.ProjectID}.cloudfunctions.net/BqDispatch

      echo:
        action: gcp/cloudfunctions:deploy
        comments: echo CF is used by one of e2e test calling HTTP API
        '@name': Echo
        timeout: 30s
        availableMemoryMb: 128
        entryPoint: Echo
        runtime: go121
        serviceAccountEmail: ${gcp.serviceAccount}
        source:
          URL: ${appPath}/e2e/echo

      monitor:
        action: gcp/cloudfunctions:deploy
        comments: minitor service is used by error cases
        '@name': BqMonitor
        timeout: 540s
        public: true
        availableMemoryMb: 256
        entryPoint: Monitor
        runtime: go121
        retry: true
        serviceAccountEmail: ${gcp.serviceAccount}
        environmentVariables:
          CONFIG: gs://${configBucket}/BqTail/config.json
          LOGGING: true
        source:
          URL: ${appPath}/
