init:
  target:
    URL: ssh://localhost/
    credentials: localhost
  appHost: $Hostname($target.URL)
  appPath: $WorkingDirectory(..)

  gcpCredentials: gcp-e2e
  bqCredentials: bq-e2e

  gcpSecrets: ${secrets.$gcpCredentials}
  bqSecrets: ${secrets.$bqCredentials}
  projectID: ${gcpSecrets.ProjectID}
  bqProjectID: ${bqSecrets.ProjectID}

  prefix: $Replace($projectID,'-','_')
  serviceAccount: ${gcpSecrets.ClientEmail}

  configBucket: ${prefix}_config
  triggerBucket: ${prefix}_bqtail
  dispatchBucket: ${prefix}_bqdispatch
  opsBucket: ${prefix}_operation
  exportBucket: ${prefix}_export
  mirrorBucket: ${prefix}_trigger
  tirggerBucket: ${prefix}_bqtail

  #make that json Google Secret has region key that is inline with this value
  region: us-central1

pipeline:

  init:
#    system:
#      action: run
#      request: '@system'
#      tasks: '*'
    app:
      action: run
      request: '@app'
      tasks: 'deploy'
    mon:
      action: run
      request: '@mon'


  test:
    action: run
    request: '@regression/regression'
    tasks: '*'
