pipeline:

  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.21

  package:
    action: exec:run
    target: $target
    checkError: true
    commands:
      - cd $appPath
      - export GO111MODULE=on
      - unset GOPATH
      - go mod vendor
      - go build


  bqtail:
    action: gcp/cloudfunctions:deploy
    credentials: $gcpCredentials
    '@name': BqTail
    timeout: 540s
    public: true
    availableMemoryMb: 256
    entryPoint: BqTail
    retry: true
    runtime: go121
    serviceAccountEmail: ${gcp.serviceAccount}
    environmentVariables:
      CONFIG: gs://${configBucket}/BqTail/config.json
      LOGGING: false
      GS_MAX_RETRIES: 10
      MAX_RETRIES: 10
    eventTrigger:
      eventType: google.storage.object.finalize
      resource: projects/_/buckets/${triggerBucket}
    source:
      URL: ${appPath}

  bqdisaptch:
    action: gcp/cloudfunctions:deploy
    credentials: $gcpCredentials
    '@name': BqDispatch
    timeout: 59s
    public: true
    serviceAccountEmail: ${gcp.serviceAccount}
    availableMemoryMb: 256
    entryPoint: BqDispatch
    runtime: go121
    environmentVariables:
      CONFIG: gs://${configBucket}/BqDispatch/config.json
      LOGGING: false
      GS_MAX_RETRIES: 10
      MAX_RETRIES: 10
    source:
      URL: ${appPath}

