init:

  '!gcpCredentials': $params.authWith
  '!region': $params.region
  appPath: /tmp/bqmonitor
  functionName: BqMonitor
  gcp: ${secrets.$gcpCredentials}
  serviceAccount: $gcp.ClientEmail
  projectID: $gcp.ProjectID
  prefix: $Replace(${projectID},'-','_')
  configBucket: ${prefix}_config
  tirggerBucket: ${prefix}_bqtail

pipeline:

  set_sdk:
    action: sdk.set
    target: $target
    sdk: go:1.12


  deploy:
    checkOut:
      action: vc/git:checkout
      Origin:
        URL: https://github.com/viant/bqtail.git
      Dest:
        URL: ${appPath}

    package:
      action: exec:run
      target: $target
      checkError: true
      commands:
        - export GIT_TERMINAL_PROMPT=1
        - export GO111MODULE=on
        - unset GOPATH
        - cd ${appPath}/
        - go mod vendor
        - echo 'apply cloud functiion hack'
        - mkdir -p vendor/github.com/viant/bqtail
        - cp -rf base vendor/github.com/viant/bqtail
        - cp -rf dispatch vendor/github.com/viant/bqtail
        - cp -rf mon vendor/github.com/viant/bqtail
        - cp -rf service vendor/github.com/viant/bqtail
        - cp -rf s* vendor/github.com/viant/bqtail/
        - cp -rf t* vendor/github.com/viant/bqtail/
        - go build

    upload:
      action: gcp/cloudfunctions:deploy
      credentials: $gcpCredentials
      public: true
      '@name': $functionName
      entryPoint: Monitor
      runtime: go111
      availableMemoryMb: 256
      timeout: 540s
      serviceAccountEmail: $serviceAccount
      environmentVariables:
        CONFIG: gs://${configBucket}/BqTail/config.json
        LOGGING: 'true'
      source:
        URL: ${appPath}/
      sleepTimeMs: 5000

    scheduleMonitor:
      action: gcp/cloudscheduler:deploy
      credentials: $gcpCredentials
      name: BqMonitor
      schedule: '*/1 * * * *'
      timeZone: GMT
      httpTarget:
        headers:
          User-Agent: Google-Cloud-Scheduler
        httpMethod: GET
        uri: https://${region}-${gcp.ProjectID}.cloudfunctions.net/BqMonitor?IncludeDone=true&DestBucket=${tirggerBucket}&DestPath=sys/bqmon
